Modified lab8 so fields with comma are now processed properly.

diff --git a/lab8 b/lab8
--- a/lab8
+++ b/lab8
@@ -14,49 +14,53 @@
 # EMAIL
 # WEBURL
 #
-# Sample line from the addresses.csv file:
-# "Joey","Bolick","Utility Trailer Sales","7700 N Council Rd","Oklahoma City","Oklahoma","OK","73132","405-728-5972","405-728-5244","joey@bolick.com","http://www.joeybolick.com"
-#
-#
-# Checking if a filename has been supplied:
-if [ -z "$1" ]
-  then 
+# Sample line from the addresses.csv file (note comma in third field):
+# "Jeri","Farstvedt","Regan, Denis J Esq","16133 Ventura Blvd #-700","Encino","Los Angeles","CA","91436","818-986-8843","818-986-6786","jeri@farstvedt.com","http://www.jerifarstvedt.com"
+
+if [ -z "$1" ]					# Checking if input parameter has been supplied.
+  then
     echo "Usage:"
-    echo "$0 /var/share/CS225/addresses.csv"
+    echo "${0##*/} /var/share/CS225/addresses.csv"
     exit 123
-  else
-    VAR1=$(tac $1|grep --max-count=1 .)	# Getting the last non-empty line from the input file into a temp variable; credits: http://stackoverflow.com/a/2639060
-    VAR1=${VAR1//\"}			# Removing all the " from the temp varialbe.
-    FNAME=${VAR1%%,*}			# Copying the first field to a new variable.
-    VAR1=${VAR1#*,}			# Removing the first field from temp variable.
-    LNAME=${VAR1%%,*}			# Copying the first of remaining fields to a new variable.
-    VAR1=${VAR1#*,}			# Removing the first of remaining fields from a temp variable.
-    COMPANY=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    STREET=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    CITY=${VAR1%%,*}
-    VAR1=${VAR1#*,}; VAR1=${VAR1#*,}	# Removing first field twice since County field is not needed.
-    STATE=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    ZIP=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    HPHONE=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    WPHONE=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    EMAIL=${VAR1%%,*}
-    VAR1=${VAR1#*,}
-    WEBURL=${VAR1%%,*}
-    echo "First Name:	$FNAME"
-    echo "Last Name:	$LNAME"
-    echo "Company:	$COMPANY"
-    echo "Address:	$STREET"
-    echo "City:		$CITY"
-    echo "State:		$STATE"
-    echo "Zip Code:	$ZIP"
-    echo "Home Phone:	$HPHONE"
-    echo "Work Phone:	$WPHONE"
-    echo "Email:		$EMAIL"
-    echo "Website:	$WEBURL"
+  elif [ ! -f $1 ]				# Checking if supplied parameter is a file.
+    then
+      echo "Usage:"
+      echo "${0##*/} /var/share/CS225/addresses.csv"
+      echo
+      echo "Cannot open "$1" for reading; exiting..."
+      exit 403
 fi
+VAR1=$(tac $1|grep --max-count=1 .)		# Getting the last non-empty line from the input file into a temp variable; credits: http://stackoverflow.com/a/2639060
+VAR1=${VAR1#\"}; VAR1=${VAR1%\"}		# Removing fist and last " from the input
+FNAME=${VAR1%%\",\"*}				# Copying the first field to a new variable.
+VAR1=${VAR1#*\",\"}				# Removing the first field from temp variable.
+LNAME=${VAR1%%\",\"*}				# Copying the first of remaining fields to a new variable.
+VAR1=${VAR1#*\",\"}				# Removing the first of remaining fields from a temp variable.
+COMPANY=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+STREET=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+CITY=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}; VAR1=${VAR1#*\",\"}	# Removing first field twice since County field is not needed.
+STATE=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+ZIP=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+HPHONE=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+WPHONE=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+EMAIL=${VAR1%%\",\"*}
+VAR1=${VAR1#*\",\"}
+WEBURL=${VAR1%%\",\"*}
+echo "First Name:	$FNAME"
+echo "Last Name:	$LNAME"
+echo "Company:	$COMPANY"
+echo "Address:	$STREET"
+echo "City:		$CITY"
+echo "State:		$STATE"
+echo "Zip Code:	$ZIP"
+echo "Home Phone:	$HPHONE"
+echo "Work Phone:	$WPHONE"
+echo "Email:		$EMAIL"
+echo "Website:	$WEBURL"
